# Docs: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ".github:"

  # Maintain dependencies for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "go.mod:"
  - package-ecosystem: "gomod"
    directory: "/lib/go"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "go.mod:"

  # Maintain dependencies for Node
  - package-ecosystem: "npm"
    directory: "/lib/typescript"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "package.json:"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/lib/python"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "requirements:"


  # Maintain dependencies for Ruby
  - package-ecosystem: "bundler"
    directory: "/lib/ruby/turbine_rb"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Gemfile:"

