run:
  timeout: 5m
  skip-dirs:
    - telemetry/otelecho.*

linters-settings:
#   depguard:
#     rules:
#       main:
#         files:
#           - "**/*.go"
#           - "!*_test.go"
#        deny:
#           - pkg: "errors"
#             desc: "Use github.com/go-errors/errors instead."
#           - pkg: "github.com/pkg/errors"
#             desc: "Use github.com/go-errors/errors instead."
  gocognit:
    min-complexity: 20
  godot:
    capital: true
  ireturn:
    allow:
      # By default, it allows using errors, empty interfaces, anonymous interfaces,
      # and interfaces provided by the standard library.
      - anon
      - error
      - empty
      - stdlib
      # Custom rules.
      - github.com/meroxa/turbine-core/pkg/record
      - slog.Handler
  nolintlint:
    allow-unused: false # Report any unused nolint directives.
    require-explanation: true # Require an explanation for nolint directives.
    require-specific: true # Require nolint directives to mention the specific linter being suppressed.
#   wrapcheck:
#     ignoreSigs:
#       # Default sigs.
#       - .Errorf(
#       - errors.New(
#       - errors.Unwrap(
#       - errors.Join(
#       - .WorkflowResult(
#       - .Wrap(
#       - .Wrapf(
#       - .WithMessage(
#       - .WithMessagef(
#       - .WithStack(
#       # Other custom sigs
#       - (log/slog.Handler).Handle
#     ignorePackageGlobs:
#       - github.com/go-errors/errors

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - dogsled
        - goconst
        - goerr113
        - gosec
        - gocognit
        - errcheck
        - forcetypeassert
        - funlen
        - dupl # re-enable after refactoring
    - path: spec_test\.go
      linters:
        - godot

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - godot
    # - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    # - musttag # fails in go workspaces (see https://github.com/tmzane/musttag/pull/63), TODO: enable when updating golangci-lint and its fixed
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
   #  - wrapcheck
    - zerologlint
