# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: turbine/v1/turbine.proto for package 'turbine_core'

require 'grpc'
require_relative 'turbine_pb'

module TurbineCore
  module TurbineService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'turbine_core.TurbineService'

      rpc :Init, ::TurbineCore::InitRequest, ::Google::Protobuf::Empty
      rpc :GetResource, ::TurbineCore::NameOrUUID, ::TurbineCore::Resource
      rpc :ReadCollection, ::TurbineCore::ReadCollectionRequest, ::TurbineCore::Collection
      rpc :WriteCollectionToResource, ::TurbineCore::WriteCollectionRequest, ::Google::Protobuf::Empty
      rpc :AddProcessToCollection, ::TurbineCore::ProcessCollectionRequest, ::TurbineCore::Collection
      rpc :RegisterSecret, ::TurbineCore::Secret, ::Google::Protobuf::Empty
      rpc :ListFunctions, ::Google::Protobuf::Empty, ::TurbineCore::ListFunctionsResponse
      rpc :ListResources, ::Google::Protobuf::Empty, ::TurbineCore::ListResourcesResponse
    end

    Stub = Service.rpc_stub_class
  end
end
