// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: process/v2/process_v2.proto

package processv2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ProcessRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ProcessRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProcessRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ProcessRequestMultiError,
// or nil if none found.
func (m *ProcessRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ProcessRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRecords() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProcessRequestValidationError{
						field:  fmt.Sprintf("Records[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProcessRequestValidationError{
						field:  fmt.Sprintf("Records[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProcessRequestValidationError{
					field:  fmt.Sprintf("Records[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProcessRequestMultiError(errors)
	}

	return nil
}

// ProcessRequestMultiError is an error wrapping multiple validation errors
// returned by ProcessRequest.ValidateAll() if the designated constraints
// aren't met.
type ProcessRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProcessRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProcessRequestMultiError) AllErrors() []error { return m }

// ProcessRequestValidationError is the validation error returned by
// ProcessRequest.Validate if the designated constraints aren't met.
type ProcessRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProcessRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProcessRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProcessRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProcessRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProcessRequestValidationError) ErrorName() string { return "ProcessRequestValidationError" }

// Error satisfies the builtin error interface
func (e ProcessRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProcessRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProcessRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProcessRequestValidationError{}

// Validate checks the field values on ProcessResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ProcessResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ProcessResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ProcessResponseMultiError, or nil if none found.
func (m *ProcessResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ProcessResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRecords() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ProcessResponseValidationError{
						field:  fmt.Sprintf("Records[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ProcessResponseValidationError{
						field:  fmt.Sprintf("Records[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ProcessResponseValidationError{
					field:  fmt.Sprintf("Records[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ProcessResponseMultiError(errors)
	}

	return nil
}

// ProcessResponseMultiError is an error wrapping multiple validation errors
// returned by ProcessResponse.ValidateAll() if the designated constraints
// aren't met.
type ProcessResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ProcessResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ProcessResponseMultiError) AllErrors() []error { return m }

// ProcessResponseValidationError is the validation error returned by
// ProcessResponse.Validate if the designated constraints aren't met.
type ProcessResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ProcessResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ProcessResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ProcessResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ProcessResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ProcessResponseValidationError) ErrorName() string { return "ProcessResponseValidationError" }

// Error satisfies the builtin error interface
func (e ProcessResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sProcessResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ProcessResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ProcessResponseValidationError{}
