// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: turbine/0.3.0/turbine.proto

package core

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TurbineServiceClient is the client API for TurbineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TurbineServiceClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*Source, error)
	GetDestination(ctx context.Context, in *GetDestinationRequest, opts ...grpc.CallOption) (*Destination, error)
	ReadCollection(ctx context.Context, in *ReadCollectionRequest, opts ...grpc.CallOption) (*Collection, error)
	WriteCollectionToDestination(ctx context.Context, in *WriteCollectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddProcessToCollection(ctx context.Context, in *ProcessCollectionRequest, opts ...grpc.CallOption) (*Collection, error)
	HasFunctions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
	GetSpec(ctx context.Context, in *GetSpecRequest, opts ...grpc.CallOption) (*GetSpecResponse, error)
}

type turbineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTurbineServiceClient(cc grpc.ClientConnInterface) TurbineServiceClient {
	return &turbineServiceClient{cc}
}

func (c *turbineServiceClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/turbine_core.TurbineService/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turbineServiceClient) GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*Source, error) {
	out := new(Source)
	err := c.cc.Invoke(ctx, "/turbine_core.TurbineService/GetSource", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turbineServiceClient) GetDestination(ctx context.Context, in *GetDestinationRequest, opts ...grpc.CallOption) (*Destination, error) {
	out := new(Destination)
	err := c.cc.Invoke(ctx, "/turbine_core.TurbineService/GetDestination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turbineServiceClient) ReadCollection(ctx context.Context, in *ReadCollectionRequest, opts ...grpc.CallOption) (*Collection, error) {
	out := new(Collection)
	err := c.cc.Invoke(ctx, "/turbine_core.TurbineService/ReadCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turbineServiceClient) WriteCollectionToDestination(ctx context.Context, in *WriteCollectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/turbine_core.TurbineService/WriteCollectionToDestination", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turbineServiceClient) AddProcessToCollection(ctx context.Context, in *ProcessCollectionRequest, opts ...grpc.CallOption) (*Collection, error) {
	out := new(Collection)
	err := c.cc.Invoke(ctx, "/turbine_core.TurbineService/AddProcessToCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turbineServiceClient) HasFunctions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, "/turbine_core.TurbineService/HasFunctions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *turbineServiceClient) GetSpec(ctx context.Context, in *GetSpecRequest, opts ...grpc.CallOption) (*GetSpecResponse, error) {
	out := new(GetSpecResponse)
	err := c.cc.Invoke(ctx, "/turbine_core.TurbineService/GetSpec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TurbineServiceServer is the server API for TurbineService service.
// All implementations should embed UnimplementedTurbineServiceServer
// for forward compatibility
type TurbineServiceServer interface {
	Init(context.Context, *InitRequest) (*emptypb.Empty, error)
	GetSource(context.Context, *GetSourceRequest) (*Source, error)
	GetDestination(context.Context, *GetDestinationRequest) (*Destination, error)
	ReadCollection(context.Context, *ReadCollectionRequest) (*Collection, error)
	WriteCollectionToDestination(context.Context, *WriteCollectionRequest) (*emptypb.Empty, error)
	AddProcessToCollection(context.Context, *ProcessCollectionRequest) (*Collection, error)
	HasFunctions(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error)
	GetSpec(context.Context, *GetSpecRequest) (*GetSpecResponse, error)
}

// UnimplementedTurbineServiceServer should be embedded to have forward compatible implementations.
type UnimplementedTurbineServiceServer struct {
}

func (UnimplementedTurbineServiceServer) Init(context.Context, *InitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedTurbineServiceServer) GetSource(context.Context, *GetSourceRequest) (*Source, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSource not implemented")
}
func (UnimplementedTurbineServiceServer) GetDestination(context.Context, *GetDestinationRequest) (*Destination, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDestination not implemented")
}
func (UnimplementedTurbineServiceServer) ReadCollection(context.Context, *ReadCollectionRequest) (*Collection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCollection not implemented")
}
func (UnimplementedTurbineServiceServer) WriteCollectionToDestination(context.Context, *WriteCollectionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteCollectionToDestination not implemented")
}
func (UnimplementedTurbineServiceServer) AddProcessToCollection(context.Context, *ProcessCollectionRequest) (*Collection, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProcessToCollection not implemented")
}
func (UnimplementedTurbineServiceServer) HasFunctions(context.Context, *emptypb.Empty) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasFunctions not implemented")
}
func (UnimplementedTurbineServiceServer) GetSpec(context.Context, *GetSpecRequest) (*GetSpecResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSpec not implemented")
}

// UnsafeTurbineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TurbineServiceServer will
// result in compilation errors.
type UnsafeTurbineServiceServer interface {
	mustEmbedUnimplementedTurbineServiceServer()
}

func RegisterTurbineServiceServer(s grpc.ServiceRegistrar, srv TurbineServiceServer) {
	s.RegisterService(&TurbineService_ServiceDesc, srv)
}

func _TurbineService_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurbineServiceServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turbine_core.TurbineService/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurbineServiceServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurbineService_GetSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurbineServiceServer).GetSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turbine_core.TurbineService/GetSource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurbineServiceServer).GetSource(ctx, req.(*GetSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurbineService_GetDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurbineServiceServer).GetDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turbine_core.TurbineService/GetDestination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurbineServiceServer).GetDestination(ctx, req.(*GetDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurbineService_ReadCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurbineServiceServer).ReadCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turbine_core.TurbineService/ReadCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurbineServiceServer).ReadCollection(ctx, req.(*ReadCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurbineService_WriteCollectionToDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurbineServiceServer).WriteCollectionToDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turbine_core.TurbineService/WriteCollectionToDestination",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurbineServiceServer).WriteCollectionToDestination(ctx, req.(*WriteCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurbineService_AddProcessToCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurbineServiceServer).AddProcessToCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turbine_core.TurbineService/AddProcessToCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurbineServiceServer).AddProcessToCollection(ctx, req.(*ProcessCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurbineService_HasFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurbineServiceServer).HasFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turbine_core.TurbineService/HasFunctions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurbineServiceServer).HasFunctions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TurbineService_GetSpec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TurbineServiceServer).GetSpec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turbine_core.TurbineService/GetSpec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TurbineServiceServer).GetSpec(ctx, req.(*GetSpecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TurbineService_ServiceDesc is the grpc.ServiceDesc for TurbineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TurbineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "turbine_core.TurbineService",
	HandlerType: (*TurbineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _TurbineService_Init_Handler,
		},
		{
			MethodName: "GetSource",
			Handler:    _TurbineService_GetSource_Handler,
		},
		{
			MethodName: "GetDestination",
			Handler:    _TurbineService_GetDestination_Handler,
		},
		{
			MethodName: "ReadCollection",
			Handler:    _TurbineService_ReadCollection_Handler,
		},
		{
			MethodName: "WriteCollectionToDestination",
			Handler:    _TurbineService_WriteCollectionToDestination_Handler,
		},
		{
			MethodName: "AddProcessToCollection",
			Handler:    _TurbineService_AddProcessToCollection_Handler,
		},
		{
			MethodName: "HasFunctions",
			Handler:    _TurbineService_HasFunctions_Handler,
		},
		{
			MethodName: "GetSpec",
			Handler:    _TurbineService_GetSpec_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "turbine/0.3.0/turbine.proto",
}
