# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: process_v1.proto for package 'io.meroxa.funtime'

require 'grpc'
require 'process_v1_pb'

module Io
  module Meroxa
    module Funtime
      module Function
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'io.meroxa.funtime.Function'

          rpc :Process, ::Io::Meroxa::Funtime::ProcessRecordRequest, ::Io::Meroxa::Funtime::ProcessRecordResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
