# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: turbine_v2.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'
require 'validate/validate_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("turbine_v2.proto", :syntax => :proto3) do
    add_message "turbine_core_v2.InitRequest" do
      optional :appName, :string, 1
      optional :configFilePath, :string, 2
      optional :language, :enum, 3, "turbine_core_v2.Language"
      optional :gitSHA, :string, 4
      optional :turbineVersion, :string, 5
    end
    add_message "turbine_core_v2.AddSourceRequest" do
      optional :name, :string, 1
      optional :plugin, :message, 2, "turbine_core_v2.Plugin"
    end
    add_message "turbine_core_v2.AddSourceResponse" do
      optional :streamName, :string, 1
    end
    add_message "turbine_core_v2.ReadRecordsRequest" do
      optional :sourceStream, :string, 1
    end
    add_message "turbine_core_v2.ReadRecordsResponse" do
      optional :streamRecords, :message, 1, "turbine_core_v2.StreamRecords"
    end
    add_message "turbine_core_v2.ProcessRecordsRequest" do
      optional :process, :message, 1, "turbine_core_v2.ProcessRecordsRequest.Process"
      optional :streamRecords, :message, 2, "turbine_core_v2.StreamRecords"
    end
    add_message "turbine_core_v2.ProcessRecordsRequest.Process" do
      optional :name, :string, 1
    end
    add_message "turbine_core_v2.ProcessRecordsResponse" do
      optional :streamRecords, :message, 1, "turbine_core_v2.StreamRecords"
    end
    add_message "turbine_core_v2.AddDestinationRequest" do
      optional :name, :string, 1
      optional :plugin, :message, 2, "turbine_core_v2.Plugin"
    end
    add_message "turbine_core_v2.AddDestinationResponse" do
      optional :streamName, :string, 1
    end
    add_message "turbine_core_v2.WriteRecordsRequest" do
      optional :destinationID, :string, 1
      optional :streamRecords, :message, 2, "turbine_core_v2.StreamRecords"
    end
    add_message "turbine_core_v2.GetSpecRequest" do
      optional :image, :string, 1
    end
    add_message "turbine_core_v2.GetSpecResponse" do
      optional :spec, :bytes, 1
    end
    add_message "turbine_core_v2.StreamRecords" do
      optional :streamName, :string, 1
      repeated :records, :message, 2, "turbine_core_v2.Record"
    end
    add_message "turbine_core_v2.Record" do
      optional :key, :string, 1
      optional :value, :bytes, 2
      optional :timestamp, :message, 3, "google.protobuf.Timestamp"
    end
    add_message "turbine_core_v2.Plugin" do
      optional :name, :string, 1
      map :config, :string, :string, 2
    end
    add_enum "turbine_core_v2.Language" do
      value :GOLANG, 0
      value :PYTHON, 1
      value :JAVASCRIPT, 2
      value :RUBY, 3
    end
  end
end

module TurbineCoreV2
  InitRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.InitRequest").msgclass
  AddSourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.AddSourceRequest").msgclass
  AddSourceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.AddSourceResponse").msgclass
  ReadRecordsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.ReadRecordsRequest").msgclass
  ReadRecordsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.ReadRecordsResponse").msgclass
  ProcessRecordsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.ProcessRecordsRequest").msgclass
  ProcessRecordsRequest::Process = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.ProcessRecordsRequest.Process").msgclass
  ProcessRecordsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.ProcessRecordsResponse").msgclass
  AddDestinationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.AddDestinationRequest").msgclass
  AddDestinationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.AddDestinationResponse").msgclass
  WriteRecordsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.WriteRecordsRequest").msgclass
  GetSpecRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.GetSpecRequest").msgclass
  GetSpecResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.GetSpecResponse").msgclass
  StreamRecords = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.StreamRecords").msgclass
  Record = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.Record").msgclass
  Plugin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.Plugin").msgclass
  Language = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core_v2.Language").enummodule
end
