# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: turbine.proto for package 'turbine_core'

require 'grpc'
require 'turbine_pb'

module TurbineCore
  module TurbineService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'turbine_core.TurbineService'

      rpc :Init, ::TurbineCore::InitRequest, ::Google::Protobuf::Empty
      rpc :GetResource, ::TurbineCore::GetResourceRequest, ::TurbineCore::Resource
      rpc :ReadCollection, ::TurbineCore::ReadCollectionRequest, ::TurbineCore::Collection
      rpc :WriteCollectionToResource, ::TurbineCore::WriteCollectionRequest, ::Google::Protobuf::Empty
      rpc :AddProcessToCollection, ::TurbineCore::ProcessCollectionRequest, ::TurbineCore::Collection
      rpc :RegisterSecret, ::TurbineCore::Secret, ::Google::Protobuf::Empty
      rpc :HasFunctions, ::Google::Protobuf::Empty, ::Google::Protobuf::BoolValue
      rpc :ListResources, ::Google::Protobuf::Empty, ::TurbineCore::ListResourcesResponse
      rpc :GetSpec, ::Google::Protobuf::Empty, ::TurbineCore::GetSpecResponse
    end

    Stub = Service.rpc_stub_class
  end
end
