# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: turbine.proto for package 'turbine_core'

require 'grpc'
require 'turbine_pb'

module TurbineCore
  module TurbineService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'turbine_core.TurbineService'

      rpc :Init, ::TurbineCore::InitRequest, ::Google::Protobuf::Empty
      rpc :GetSource, ::TurbineCore::GetSourceRequest, ::TurbineCore::Source
      rpc :GetDestination, ::TurbineCore::GetDestinationRequest, ::TurbineCore::Destination
      rpc :ReadCollection, ::TurbineCore::ReadCollectionRequest, ::TurbineCore::Collection
      rpc :WriteCollectionToDestination, ::TurbineCore::WriteCollectionRequest, ::Google::Protobuf::Empty
      rpc :AddProcessToCollection, ::TurbineCore::ProcessCollectionRequest, ::TurbineCore::Collection
      rpc :HasFunctions, ::Google::Protobuf::Empty, ::Google::Protobuf::BoolValue
      rpc :GetSpec, ::TurbineCore::GetSpecRequest, ::TurbineCore::GetSpecResponse
    end

    Stub = Service.rpc_stub_class
  end
end
