# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: turbine.proto for package 'turbine_core'

require 'grpc'
require 'turbine_pb'

module TurbineCore
  module TurbineService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'turbine_core.TurbineService'

      rpc :Init, ::TurbineCore::InitRequest, ::Google::Protobuf::Empty
      # todo consider one method parameterized with connector type
      rpc :ReadFromSource, ::TurbineCore::ReadFromSourceRequest, ::TurbineCore::RecordsCollection
      rpc :Process, ::TurbineCore::ProcessRecordsRequest, ::TurbineCore::RecordsCollection
      rpc :WriteToDestination, ::TurbineCore::WriteToDestinationRequest, ::Google::Protobuf::Empty
      # needed in CLI to know if a build is needed or not
      rpc :HasFunctions, ::Google::Protobuf::Empty, ::Google::Protobuf::BoolValue
      # needed in the CLI for the deployment spec
      rpc :GetSpec, ::TurbineCore::GetSpecRequest, ::TurbineCore::GetSpecResponse
    end

    Stub = Service.rpc_stub_class
  end
end
