# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: turbine.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'
require 'google/protobuf/wrappers_pb'
require 'validate/validate_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("turbine.proto", :syntax => :proto3) do
    add_message "turbine_core.ReadFromSourceRequest" do
      optional :pluginName, :string, 1
      optional :direction, :enum, 2, "turbine_core.ReadFromSourceRequest.Direction"
      optional :configuration, :message, 3, "turbine_core.Configurations"
    end
    add_enum "turbine_core.ReadFromSourceRequest.Direction" do
      value :SOURCE, 0
      value :DESTINATION, 1
    end
    add_message "turbine_core.WriteToDestinationRequest" do
      optional :pluginName, :string, 1
      optional :configuration, :message, 2, "turbine_core.Configurations"
      optional :records, :message, 3, "turbine_core.RecordsCollection"
    end
    add_message "turbine_core.InitRequest" do
      optional :appName, :string, 1
      optional :configFilePath, :string, 2
      optional :language, :enum, 3, "turbine_core.Language"
      optional :gitSHA, :string, 4
      optional :turbineVersion, :string, 5
    end
    add_message "turbine_core.RecordsCollection" do
      repeated :records, :message, 1, "turbine_core.Record"
      optional :stream, :string, 2
    end
    add_message "turbine_core.Record" do
      optional :key, :string, 1
      optional :value, :bytes, 2
      optional :timestamp, :message, 3, "google.protobuf.Timestamp"
    end
    add_message "turbine_core.Configurations" do
      repeated :configuration, :message, 1, "turbine_core.Configuration"
    end
    add_message "turbine_core.Configuration" do
      optional :field, :string, 1
      optional :value, :string, 2
    end
    add_message "turbine_core.ProcessRecordsRequest" do
      optional :process, :message, 1, "turbine_core.ProcessRecordsRequest.Process"
      optional :records, :message, 2, "turbine_core.RecordsCollection"
    end
    add_message "turbine_core.ProcessRecordsRequest.Process" do
      optional :name, :string, 1
    end
    add_message "turbine_core.Secret" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
    add_message "turbine_core.GetSpecRequest" do
      optional :image, :string, 1
    end
    add_message "turbine_core.GetSpecResponse" do
      optional :spec, :bytes, 1
    end
    add_enum "turbine_core.Language" do
      value :GOLANG, 0
      value :PYTHON, 1
      value :JAVASCRIPT, 2
      value :RUBY, 3
      value :JAVA, 4
    end
  end
end

module TurbineCore
  ReadFromSourceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.ReadFromSourceRequest").msgclass
  ReadFromSourceRequest::Direction = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.ReadFromSourceRequest.Direction").enummodule
  WriteToDestinationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.WriteToDestinationRequest").msgclass
  InitRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.InitRequest").msgclass
  RecordsCollection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.RecordsCollection").msgclass
  Record = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.Record").msgclass
  Configurations = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.Configurations").msgclass
  Configuration = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.Configuration").msgclass
  ProcessRecordsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.ProcessRecordsRequest").msgclass
  ProcessRecordsRequest::Process = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.ProcessRecordsRequest.Process").msgclass
  Secret = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.Secret").msgclass
  GetSpecRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.GetSpecRequest").msgclass
  GetSpecResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.GetSpecResponse").msgclass
  Language = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("turbine_core.Language").enummodule
end
