# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in turbine_rb.gemspec
gemspec

gem "rake", "~> 13.0"

group :development, :test do
  gem "pry"
  gem "rubocop", "~> 1.21", require: false
  gem "rubocop-rake", "~> 0.6.0"
  gem "rubocop-rspec", "~> 2.15"
end

group :test do
  gem "guard-rspec"
  gem "mocktail"
  gem "rspec", "~> 3.0"
end
