# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in turbine_rb.gemspec
gemspec

gem "rake", "~> 13.0"

group :development, :test do
  gem "rubocop", "~> 1.21"
  gem "pry"
end

group :test do
  gem "mocktail"
  gem "rspec", "~> 3.0"
  gem "guard-rspec"
end