name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Generated files
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make generate
          git diff --exit-code --numstat
      - name: Run go tests
        run: make test
      - name: Run ruby tests
        run: make test_turbine_rb
