name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
           go-version-file: 'go.mod' # It will use the version specified in the go.mod file.
           cache-dependency-path: 'go.sum'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Tools
        run: make tools
      - name: Generated and format files
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make fmt generate
          git diff --exit-code --numstat
      - name: Run go tests
        run: make test
      - name: Run ruby tests
        run: make ruby-sdk-test
