name: Release ruby gem

on:
  push:
    branches:
      - main
jobs:
  check-local-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lib/ruby/turbine_rb
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MEROXA_MACHINE }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Setup dependencies
        run: bundler install

      - name: Check local version
        id: check_local
        run: echo "local_version=$(bump current)" >> $GITHUB_OUTPUT

      - name: Check published version
        id: check_published
        run: echo "published_version=$(gem info turbine_rb -r | grep -o 'turbine_rb \((.*)\)' | tr -d 'turbine_rb ()')" >> $GITHUB_OUTPUT

      - name: Publish
        if: steps.check_published.outputs.published_version != null && (steps.check_local.outputs.local_version > steps.check_published.outputs.published_version)
        env:
          GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem

      - name: Tag
        env:
          TAG: ${{ format('turbine_rb@{0}', steps.check_local.outputs.local_version) }}
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag -a $TAG -m "release: $TAG"
          git push origin $TAG

